CREATE TABLE Medico(
	ID				INT,
	NOME			VARCHAR(20)		NOT NULL,
	ESPECIALIDADE	VARCHAR(20),

	PRIMARY KEY(ID)
);

CREATE TABLE Farmacia(
	NOME		VARCHAR(20)		NOT NULL,
	ENDERECO	VARCHAR(20)		NOT NULL,
	TELEFONE	VARCHAR(9),

	PRIMARY KEY(NOME)
);

CREATE TABLE Paciente(
	UTENTE		INT,
	NOME		VARCHAR(20)		NOT NULL,
	NASCIMENTO	DATE			NOT NULL,
	ENDERECO	VARCHAR(20),

	PRIMARY KEY(UTENTE)
);

CREATE TABLE Prescricao(
	NUNICO		INT,
	DATA		DATE,
	NUTENTE		INT				NOT NULL,
	NFARMACIA	VARCHAR(20)				NOT NULL,
	NMEDICO		INT				NOT NULL,

	PRIMARY KEY(NUNICO),
	FOREIGN KEY(NUTENTE) REFERENCES Paciente(UTENTE),
	FOREIGN KEY(NFARMACIA) REFERENCES Farmacia(NOME),
	FOREIGN KEY(NMEDICO) REFERENCES Medico(ID)
);

CREATE TABLE Farmaceutica(
	NREGISTO	INT,
	NOME		VARCHAR(20)		NOT NULL,
	TELEFONE	VARCHAR(9),
	ENDERECO	VARCHAR(20)		NOT NULL,

	PRIMARY KEY(NREGISTO)
);

CREATE TABLE Farmaco(
	FORMULA		VARCHAR(20),
	NOME		VARCHAR(20)		NOT NULL,
	NFARMACEUTICA	INT,

	PRIMARY KEY(FORMULA),
	FOREIGN KEY(NFARMACEUTICA) REFERENCES Farmaceutica(NREGISTO)

);
CREATE TABLE Tem(
	NPRESCRICAO	INT,
	FORMULA		VARCHAR(20)		NOT NULL,

	PRIMARY KEY(NPRESCRICAO,FORMULA),
	FOREIGN KEY(NPRESCRICAO) REFERENCES Prescricao(NUNICO),
	FOREIGN KEY(FORMULA) REFERENCES Farmaco(FORMULA)
);

